# Generated by Django 5.2.1 on 2025-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capa',
            field=models.ImageField(default='imagens/default.jpg', upload_to='capas/'),
            preserve_default=False,
        ),
    ]
