# Generated by Django 5.2.1 on 2025-05-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capa_extra',
            field=models.ImageField(blank=True, null=True, upload_to='capas_extras/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
    ]
